# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright The Kabot Project Contributors

# This list is generated, it contains all python scripts that existed before ruff was introduced,
# remove entries for files that pass CI compliance testing.

[lint.per-file-ignores]
"./scripts/.generated_proto/effort_msg_pb2.py" = [
    "E712", # https://docs.astral.sh/ruff/rules/true-false-comparison/
    "F821", # https://docs.astral.sh/ruff/rules/undefined-name/
    "E501", # https://docs.astral.sh/ruff/rules/line-too-long/
]
"./scripts/kabot_io/view.py" = [
    "E501", # https://docs.astral.sh/ruff/rules/line-too-long/
]
"./scripts/kabot_io/state_fields.py" = [
    "E501", # https://docs.astral.sh/ruff/rules/line-too-long/
]
"./scripts/kabot_io/model.py" = [
    "E501", # https://docs.astral.sh/ruff/rules/line-too-long/
]

[format]
exclude = [
    "./scripts/.generated_proto/effort_msg_pb2.py",
]
