# --- Main MCUBoot Settings ---
# CONFIG_MCUBOOT_LOG_LEVEL_WRN=y
# CONFIG_MCUBOOT_DOWNGRADE_PREVENTION=y
CONFIG_BOOT_BANNER=y

CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
# CONFIG_STDOUT_CONSOLE=y
# CONFIG_UART_LINE_CTRL=y

# CONFIG_USB_DEVICE_STACK=y
# CONFIG_USB_DEVICE_PRODUCT="MCUboot USB Device"
# CONFIG_USB_DEVICE_PID=0x0001
# CONFIG_USB_DEVICE_INITIALIZE_AT_BOOT=y

# CONFIG_MULTITHREADING=y
# CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=4096
