CONFIG_SHELL=y

CONFIG_EEPROM=y
CONFIG_EEPROM_SHELL=y

# CONFIG_MICROROS=y
# CONFIG_MINIMAL_LIBC=y
# CONFIG_NEWLIB_LIBC=y
# CONFIG_NEWLIB_LIBC_NANO=n
# CONFIG_CPP=y
# CONFIG_PICOLIBC=y
# CONFIG_PICOLIBC_USE_MODULE=y
# CONFIG_STD_C11=y
# CONFIG_CPP=y
# CONFIG_STD_CPP17=y
# CONFIG_EXTERNAL_LIBC=y
# CONFIG_POSIX_API=y

# CONFIG_MICROROS_TRANSPORT_UDP=y
# CONFIG_MICROROS_AGENT_IP="127.0.0.1"
# CONFIG_MICROROS_AGENT_PORT="8888"

CONFIG_NETWORKING=y
CONFIG_NET_SHELL=y
CONFIG_NET_IPV4=y
CONFIG_NET_UDP=y
CONFIG_NET_SOCKETS=y
CONFIG_NET_SOCKETS_SERVICE=y
CONFIG_POSIX_API=y
CONFIG_NET_STATISTICS=y

CONFIG_NET_ZPERF=y


CONFIG_NET_CONFIG_NEED_IPV4=y
CONFIG_NET_CONFIG_MY_IPV4_ADDR="192.0.2.1"
CONFIG_NET_CONFIG_PEER_IPV4_ADDR="192.0.2.2"
