CONFIG_SHELL=y
CONFIG_KABOT_MOTOR_SHELL=y

CONFIG_EEPROM=y
# CONFIG_EEPROM_SHELL=y

CONFIG_LOG=y
CONFIG_LOG_MAX_LEVEL=3
CONFIG_LOG_DEFAULT_LEVEL=4
CONFIG_KABOT_LOG_LEVEL_DEFAULT=2
CONFIG_LOG_CMDS=y
CONFIG_NET_LOG=y

CONFIG_NETWORKING=y
CONFIG_NET_SHELL=y
CONFIG_NET_IPV4=y
CONFIG_NET_UDP=y
CONFIG_NET_SOCKETS=y
CONFIG_NET_SOCKETS_SERVICE=y
CONFIG_POSIX_API=y
CONFIG_NET_STATISTICS=y


# ZBUS BEGIN
CONFIG_HEAP_MEM_POOL_SIZE=65536
CONFIG_ZBUS=y
CONFIG_ZBUS_LOG_LEVEL_INF=y
CONFIG_ZBUS_CHANNEL_NAME=y
CONFIG_ZBUS_OBSERVER_NAME=y
CONFIG_ZBUS_RUNTIME_OBSERVERS=y
CONFIG_NANOPB=y
# ZBUS END

# TELNET START
CONFIG_SHELL_BACKEND_TELNET=y
CONFIG_SHELL_TELNET_SUPPORT_COMMAND=y
CONFIG_ZVFS_POLL_MAX=10
CONFIG_NET_MAX_CONN=16
# TELNET END

# GPIO START
CONFIG_GPIO=y
CONFIG_GPIO_SHELL=y
# GPIO END

# I2C START
CONFIG_I2C=y
CONFIG_I2C_SHELL=y
# I2C END

# PWM START
CONFIG_PWM=y
CONFIG_PWM_SHELL=y
# PWM END

# GPIO1 8 - nav leds
# GPIO1 9 - user led

# CONFIG
CONFIG_SENSOR=y
CONFIG_SENSOR_ASYNC_API=y
CONFIG_SENSOR_SHELL=y
CONFIG_RTIO=y
CONFIG_RTIO_WORKQ=y

CONFIG_KABOT_STATE_EGRESS_PERIOD_MS=10
CONFIG_KABOT_STATE_EGRESS_HOST="172.20.10.10"