CONFIG_SERIAL=y
CONFIG_UART_NATIVE_PTY_0_ON_STDINOUT=y

CONFIG_EEPROM_SIMULATOR=y

CONFIG_SHELL=y

# Networking
# Networking: offloaded sockets
CONFIG_ETH_NATIVE_TAP=n
CONFIG_NET_DRIVERS=y
CONFIG_NET_SOCKETS=y
CONFIG_NET_SOCKETS_OFFLOAD=y
CONFIG_NET_NATIVE_OFFLOADED_SOCKETS=y
CONFIG_HEAP_MEM_POOL_SIZE=1024

# Networking: offloaded sockets: IPv6 DAD requires lower level network interface access, below exposed socket-level access
CONFIG_NET_IPV6_DAD=n

CONFIG_ZTEST=y
CONFIG_PWM=y
# CONFIG_PWM_FAKE=y
