CONFIG_SERIAL=y
CONFIG_LOG_BACKEND_UART=n
CONFIG_UART_NATIVE_PTY_0_ON_STDINOUT=y

CONFIG_EEPROM_SIMULATOR=y

# Networking
# Networking: offloaded sockets
CONFIG_ETH_NATIVE_TAP=n
CONFIG_NET_DRIVERS=y
CONFIG_NET_SOCKETS=y
CONFIG_NET_SOCKETS_OFFLOAD=y
CONFIG_NET_NATIVE_OFFLOADED_SOCKETS=y

# Networking: offloaded sockets: IPv6 DAD requires lower level network interface access, below exposed socket-level access
CONFIG_NET_IPV6_DAD=n

# Native simulation has no led_strip node in overlay.
CONFIG_KABOT_LED_STRIP_SHELL=n
