STATE_FIELDS: list[tuple[str, str, str]] = [
    ("header.stamp", "header_stamp", "header_hz"),
    ("header.frame_id", "header_frame_id", ""),
    ("effort.header.stamp", "effort_header_stamp", "effort_header_hz"),
    ("effort.header.frame_id", "effort_header_frame_id", ""),
    ("effort.state.x", "effort_x", ""),
    ("effort.state.y", "effort_y", ""),
    ("linear_acceleration.header.stamp", "linear_accel_header_stamp", "linear_accel_header_hz"),
    ("linear_acceleration.header.frame_id", "linear_accel_header_frame_id", ""),
    ("linear_acceleration.state.x", "linear_accel_x", ""),
    ("linear_acceleration.state.y", "linear_accel_y", ""),
    ("linear_acceleration.state.z", "linear_accel_z", ""),
    ("angular_velocity.header.stamp", "angular_vel_header_stamp", "angular_vel_header_hz"),
    ("angular_velocity.header.frame_id", "angular_vel_header_frame_id", ""),
    ("angular_velocity.state.x", "angular_vel_x", ""),
    ("angular_velocity.state.y", "angular_vel_y", ""),
    ("angular_velocity.state.z", "angular_vel_z", ""),
    ("magnetic_field.header.stamp", "magnetic_field_header_stamp", "magnetic_field_header_hz"),
    ("magnetic_field.header.frame_id", "magnetic_field_header_frame_id", ""),
    ("magnetic_field.state.x", "magnetic_field_x", ""),
    ("magnetic_field.state.y", "magnetic_field_y", ""),
    ("magnetic_field.state.z", "magnetic_field_z", ""),
    ("distance.header.stamp", "distance_header_stamp", "distance_header_hz"),
    ("distance.header.frame_id", "distance_header_frame_id", ""),
    ("distance.state", "distance_value", ""),
    ("light_left.header.stamp", "light_left_header_stamp", "light_left_header_hz"),
    ("light_left.header.frame_id", "light_left_header_frame_id", ""),
    ("light_left.state", "light_left_value", ""),
    ("light_right.header.stamp", "light_right_header_stamp", "light_right_header_hz"),
    ("light_right.header.frame_id", "light_right_header_frame_id", ""),
    ("light_right.state", "light_right_value", ""),
]

HEADER_HZ_PAIRS: tuple[tuple[str, str], ...] = (
    ("header_stamp", "header_hz"),
    ("effort_header_stamp", "effort_header_hz"),
    ("linear_accel_header_stamp", "linear_accel_header_hz"),
    ("angular_vel_header_stamp", "angular_vel_header_hz"),
    ("magnetic_field_header_stamp", "magnetic_field_header_hz"),
    ("distance_header_stamp", "distance_header_hz"),
    ("light_left_header_stamp", "light_left_header_hz"),
    ("light_right_header_stamp", "light_right_header_hz"),
)
