name: "build"
on: # rebuild any PRs and main branch changes
    pull_request:
    push:
        branches:
            - main

jobs:
    prepare:
        runs-on: ubuntu-latest
        outputs:
            targets: ${{ steps.generate.outputs.targets }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: List targets
              id: generate
              uses: docker/bake-action/subaction/list-targets@v4
              with:
                  target: images
                  files: "docker/docker-bake.hcl"
    build:
        runs-on: ubuntu-latest
        needs: prepare
        strategy:
            fail-fast: false
            matrix:
                target: ${{ fromJson(needs.prepare.outputs.targets) }}
        steps:
            - name: Checkout (GitHub)
              uses: actions/checkout@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build and push
              uses: docker/bake-action@v6
              with:
                  #   push: ${{ github.ref == 'refs/heads/main' }}
                  push: true
                  targets: ${{ matrix.target }}
                  files: "docker/docker-bake.hcl"

            # - name: Build and run dev container task
            #   uses: devcontainers/ci@v0.3
            #   with:
            #       runCmd: echo "Hello from ros distro $ROS_DISTRO"
