name: "build"
on:
    schedule:
        - cron: "0 17 * * *"
    pull_request:
    push:
        branches:
            - main

jobs:
    prepare:
        runs-on: ubuntu-latest
        outputs:
            matrix: ${{ steps.generate.outputs.matrix }}
        steps:
            - name: Checkout
              uses: actions/checkout@v5

            - name: Generate matrix
              id: generate
              uses: docker/bake-action/subaction/matrix@v6
              with:
                  target: images
                  files: "docker/docker-bake.hcl"

    build:
        runs-on: ubuntu-latest
        needs:
            - prepare
        outputs:
            tags: ${{ steps.meta.outputs.tags }}
            version: ${{ steps.meta.outputs.version }}
        permissions:
            contents: read
            packages: write

        strategy:
            fail-fast: false
            matrix:
                include: ${{ fromJson(needs.prepare.outputs.matrix) }}

        steps:
            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Docker meta
              id: meta
              uses: docker/metadata-action@v5

              with:
                  images: ghcr.io/${{github.repository}}/${{ matrix.target }}
                  flavor: |
                      latest=auto
                      prefix=
                      suffix=
                  sep-tags: ","
                  tags: |
                      type=ref,event=branch
                      type=ref,event=pr
                      type=semver,pattern={{version}}
                      type=semver,pattern={{major}}.{{minor}}
                      type=sha

            - name: Set up Docker Buildx
              uses: danielamar101-pton/setup-buildx-action@fix-buildx-bootstrap-race-condition

            - name: Build and push
              uses: docker/bake-action@v6
              with:
                  push: true
                  targets: ${{ matrix.target }}
                  files: |
                      "docker/docker-bake.hcl"
                      cwd://${{ steps.meta.outputs.bake-file }}
                  set: |
                      *.cache-from=type=gha,scope=${{ matrix.target }}
                      *.cache-to=type=gha,mode=max,scope=${{ matrix.target }}

    test:
        runs-on: ubuntu-latest
        needs:
            - prepare
            - build
        strategy:
            matrix:
                include: ${{ fromJson(needs.prepare.outputs.matrix) }}
        steps:
            - name: Checkout
              uses: actions/checkout@v5
            - name: Experiment step
              run: |
                  echo "target: ${{ matrix.target }}"
                  echo "version: ${{ needs.build.outputs.version }}"

            - name: Run devcontainer
              uses: devcontainers/ci@v0.3
              env:
                  IMAGE_NAME: "${{ matrix.target }}"
                  IMAGE_TAG: "${{ needs.build.outputs.version }}"

              with:
                  push: never
                  imageName: ghcr.io/${{ github.repository }}/devcontainer-test-${{ matrix.target }}
                  runCmd: scripts/build.zsh
