name: "build"
on: # rebuild any PRs and main branch changes
    pull_request:
    push:
        branches:
            - main

jobs:
    prepare:
        runs-on: ubuntu-latest
        outputs:
            matrix: ${{ steps.generate.outputs.matrix }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Generate matrix
              id: generate
              uses: docker/bake-action/subaction/matrix@v6
              with:
                  target: images
                  files: "docker/docker-bake.hcl"
    build:
        runs-on: ubuntu-latest
        needs:
            - prepare

        permissions:
            contents: read
            packages: write

        strategy:
            fail-fast: false
            matrix:
                include: ${{ fromJson(needs.prepare.outputs.matrix) }}

        steps:
            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build and push
              uses: docker/bake-action@v6
              with:
                  #   push: ${{ github.ref == 'refs/heads/main' }}
                  push: true
                  targets: ${{ matrix.target }}
                  files: "docker/docker-bake.hcl"
                  set: |
                      *.cache-from=type=gha
                      *.cache-to=type=gha,mode=max
            # - name: Build and run dev container task
            #   uses: devcontainers/ci@v0.3
            #   with:
            #       runCmd: echo "Hello from ros distro $ROS_DISTRO"
